import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, ArrowRight, Bot, BriefcaseBusiness, CheckCircle2, ChevronDown, Clock3, Filter, GitBranch, Network, Search, ShieldAlert, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { EmptyState, ErrorState, GraphLoader, PageIntro, Panel, PanelTitle, RiskBadge, ScoreRing } from '../components/UI'
import { api, errorMessage } from '../lib/api'
import type { Alert, InvestigationCase } from '../types'

export default function Alerts() {
  const navigate=useNavigate(); const [severity,setSeverity]=useState('ALL'); const [status,setStatus]=useState('ALL'); const [search,setSearch]=useState('')
  const {data=[],isLoading,error}=useQuery<Alert[]>({queryKey:['alerts'],queryFn:()=>api.get('/alerts').then((response)=>response.data),refetchInterval:6000})
  const filtered=useMemo(()=>data.filter((item)=>(severity==='ALL'||item.severity===severity)&&(status==='ALL'||item.status===status)&&(!search||`${item.title} ${item.explanation}`.toLowerCase().includes(search.toLowerCase()))),[data,severity,status,search])
  if(isLoading)return <GraphLoader label="Loading explainable fraud alerts"/>
  if(error)return <ErrorState message={errorMessage(error)}/>
  return <><PageIntro eyebrow="Explainable detection queue" title="Alert center" text="Prioritize model-generated alerts, review the evidence, and route decisions into investigations." actions={<div className="queue-count"><ShieldAlert/><span><b>{data.filter((item)=>item.status==='NEW').length} new</b><small>{data.length} total alerts</small></span></div>}/><Panel className="alerts-panel"><div className="list-toolbar"><label className="search-field"><Search/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search explanation or alert"/></label><label className="filter-select"><Filter/><select value={severity} onChange={(event)=>setSeverity(event.target.value)}><option>ALL</option><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><ChevronDown/></label><label className="filter-select"><select value={status} onChange={(event)=>setStatus(event.target.value)}><option>ALL</option><option>NEW</option><option>UNDER_REVIEW</option><option>ESCALATED</option><option>CONFIRMED_FRAUD</option><option>FALSE_POSITIVE</option><option>CLOSED</option></select><ChevronDown/></label></div>{filtered.length?<div className="alert-list">{filtered.map((alert)=><button key={alert.id} onClick={()=>navigate(`/app/alerts/${alert.id}`)}><div className={`alert-severity-line line-${alert.severity.toLowerCase()}`}/><div className="alert-main"><span><RiskBadge level={alert.severity}/><small>{new Date(alert.created_at).toLocaleString()}</small></span><h3>{alert.title}</h3><p>{alert.explanation}</p></div><div className="alert-context"><span>STATUS</span><b>{alert.status.replace('_',' ')}</b><small>{alert.assigned_to?'Assigned':'Unassigned'}</small></div><div className="alert-probability"><b>{Math.round(alert.risk_score*100)}</b><span>risk score</span></div><ArrowRight/></button>)}</div>:<EmptyState title="No alerts match this queue" text="Adjust filters or start simulation to generate persisted alerts from scored events."/>}</Panel></>
}

export function AlertDetail() {
  const {alertId=''}=useParams(); const client=useQueryClient(); const [summary,setSummary]=useState<string|null>(null)
  const {data:alert,isLoading,error}=useQuery<Alert>({queryKey:['alert',alertId],queryFn:()=>api.get(`/alerts/${alertId}`).then((response)=>response.data),enabled:!!alertId})
  const update=useMutation({mutationFn:(status:string)=>api.patch(`/alerts/${alertId}`,{status}),onSuccess:()=>{toast.success('Alert status updated');client.invalidateQueries({queryKey:['alert',alertId]});client.invalidateQueries({queryKey:['alerts']})},onError:(err)=>toast.error(errorMessage(err))})
  const createCase=useMutation({mutationFn:()=>api.post<InvestigationCase>('/cases',{title:`Investigation · ${alert?.title}`,severity:alert?.severity,alert_ids:[alertId],evidence:alert?.evidence??{}}),onSuccess:({data})=>{toast.success(`Case ${data.id.slice(0,8)} created`)},onError:(err)=>toast.error(errorMessage(err))})
  const summarize=useMutation({mutationFn:()=>api.post('/assistant/summarize-alert',{alert_id:alertId}),onSuccess:({data})=>setSummary(data.summary??data.message),onError:(err)=>toast.error(errorMessage(err))})
  if(isLoading)return <GraphLoader label="Tracing alert evidence"/>
  if(error||!alert)return <ErrorState message={errorMessage(error)}/>
  const factors=(alert.evidence.factors??[]).map((factor)=>({name:factor.label,value:Math.round(factor.contribution*100)}))
  return <><Link className="back-link" to="/app/alerts"><ArrowLeft/> Alert center</Link><PageIntro eyebrow={`Explainability / ${alert.id.slice(0,8).toUpperCase()}`} title="Why was this flagged?" text="A grounded view of model output, structured evidence, and the connected signal path." actions={<div className="alert-detail-actions"><button onClick={()=>update.mutate('UNDER_REVIEW')}>Begin review</button><button className="button-primary" onClick={()=>createCase.mutate()}><BriefcaseBusiness/> Create case</button></div>}/>
    <div className="xai-detail-grid"><Panel className="xai-score-panel"><div className="probability-hero"><ScoreRing value={alert.risk_score} size={128}/><div><RiskBadge level={alert.severity}/><h2>{alert.title}</h2><p>{alert.explanation}</p></div></div><div className="prediction-meta"><div><span>Model used</span><b>{alert.evidence.model_version??'time-aware-graph-ensemble-v1'}</b></div><div><span>Prediction timestamp</span><b>{alert.evidence.prediction_timestamp?new Date(alert.evidence.prediction_timestamp).toLocaleString():new Date(alert.created_at).toLocaleString()}</b></div><div><span>Review status</span><b>{alert.status.replace('_',' ')}</b></div></div></Panel>
      <Panel className="feature-panel"><PanelTitle>Feature importance</PanelTitle><ResponsiveContainer width="100%" height={260}><BarChart data={factors} layout="vertical" margin={{left:22,right:15}}><XAxis type="number" hide/><Tooltip contentStyle={{background:'#100e18',border:'1px solid #ffffff17',borderRadius:12}}/><Bar dataKey="value" fill="#9270ef" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></Panel>
      <Panel className="evidence-detail"><PanelTitle aside={<Sparkles/>}>Evidence panel</PanelTitle><div className="evidence-tiles">{alert.evidence.reasons?.map((reason,index)=><article key={reason}><span>{index===0?<Network/>:index===1?<Clock3/>:<GitBranch/>}</span><div><small>VERIFIED SIGNAL {String(index+1).padStart(2,'0')}</small><p>{reason}</p></div></article>)}</div></Panel>
      <Panel className="timeline-panel"><PanelTitle>Suspicious timeline</PanelTitle><div className="event-timeline"><div><i/><span><small>{new Date(alert.created_at).toLocaleTimeString()}</small><b>Transaction ingested</b><p>Workspace-scoped event persisted before inference.</p></span></div><div><i/><span><small>+ feature cycle</small><b>Temporal and graph features resolved</b><p>{alert.evidence.reasons?.[0]??'Combined signal features computed.'}</p></span></div><div><i/><span><small>+ inference cycle</small><b>{Math.round(alert.risk_score*100)}% fraud probability</b><p>Alert persisted with model version and evidence snapshot.</p></span></div></div></Panel>
      <Panel className="assistant-panel"><PanelTitle aside={<Bot/>}>Grounded AI briefing</PanelTitle>{summary?<p className="ai-summary">{summary}</p>:<div className="assistant-empty"><Bot/><h3>Summarize verified evidence</h3><p>The assistant receives only this alert’s stored evidence and cannot make the fraud decision.</p><button onClick={()=>summarize.mutate()} disabled={summarize.isPending}>{summarize.isPending?'Generating…':'Generate briefing'}</button></div>}</Panel>
      <Panel className="decision-panel"><PanelTitle>Analyst decision</PanelTitle><p>Human judgment remains the final control. Update the alert after reviewing the connected evidence.</p><div><button onClick={()=>update.mutate('CONFIRMED_FRAUD')}><CheckCircle2/> Confirm fraud</button><button onClick={()=>update.mutate('FALSE_POSITIVE')}>Mark false positive</button><button onClick={()=>update.mutate('ESCALATED')}>Escalate</button></div></Panel>
    </div></>
}

